In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import r2_score, accuracy_score,classification_report,confusion_matrix

df=pd.read_csv('Social_Network_Ads.csv')
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [2]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]

In [3]:
X= df.drop(['User ID','Purchased'],axis=1)
y= df['Purchased']

In [4]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X , y , test_size=0.3 , random_state=42)

In [5]:
model = LogisticRegression()
model.fit(x_train , y_train)
y_pred = model.predict(x_test)

C:\Users\Moga\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [6]:
e=model.score(x_test,y_test)
print(f"Accuracy  = {e * 100:.2f} %")

Accuracy  = 85.83 %

In [7]:
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
X= df.drop(['User ID','Purchased'],axis=1)
y= df['Purchased']
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X , y , test_size=0.3 , random_state=42)
model = DecisionTreeClassifier(criterion='gini',max_depth=2)
model.fit(x_train , y_train)
y_pred = model.predict(x_test)
e=model.score(x_test,y_test)
print(f"Accuracy  = {e * 100:.2f} %")

Accuracy  = 93.33 %

In [8]:
X= df.drop(['User ID','Purchased'],axis=1)
y= df['Purchased']
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X , y , test_size=0.3 , random_state=42)
model = DecisionTreeClassifier(criterion='entropy',max_depth=2)
model.fit(x_train , y_train)
y_pred = model.predict(x_test)
e=model.score(x_test,y_test)
print(f"Accuracy  = {e * 100:.2f} %")

Accuracy  = 93.33 %

In [9]:
X= df.drop(['User ID','Purchased'],axis=1)
y= df['Purchased']
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X , y , test_size=0.3 , random_state=42)
model = RandomForestClassifier(max_depth=5, n_estimators=7, random_state=0)
model.fit(x_train , y_train)
y_pred = model.predict(x_test)
e=model.score(x_test,y_test)
print(f"Accuracy  = {e * 100:.2f} %")

Accuracy  = 92.50 %

In [10]:
X= df.drop(['User ID','Purchased'],axis=1)
y= df['Purchased']
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X , y , test_size=0.3 , random_state=42)
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
dic={
    'LogisticRegression':LogisticRegression(),
    'RandomeForestClassifier':RandomForestClassifier(max_depth=5, n_estimators=7, random_state=0),
    'KNeighborsClassifier':KNeighborsClassifier(n_neighbors=15,metric='manhattan'),
    'DecisionTreeClassifier':DecisionTreeClassifier(criterion='entropy', max_depth=2),
    'Support Vector Machine':SVC(kernel='linear'),
}

from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
def accuracy(y_test,y_pred):
    acc = accuracy_score(y_test,y_pred)
    return acc
    
accuracy_models=[]

models_names = []
for model_name , model in dic.items():
    model.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    accuracy_models.append(accuracy(y_test,y_pred))
    models_names.append(model_name)
    print(classification_report(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
    print('++++++++++++++++++++++++++++++++++++++')

              precision    recall  f1-score   support

           0       0.83      0.97      0.89        73
           1       0.94      0.68      0.79        47

    accuracy                           0.86       120
   macro avg       0.88      0.83      0.84       120
weighted avg       0.87      0.86      0.85       120

[[71  2]
 [15 32]]
++++++++++++++++++++++++++++++++++++++
              precision    recall  f1-score   support

           0       0.96      0.92      0.94        73
           1       0.88      0.94      0.91        47

    accuracy                           0.93       120
   macro avg       0.92      0.93      0.92       120
weighted avg       0.93      0.93      0.93       120

[[67  6]
 [ 3 44]]
++++++++++++++++++++++++++++++++++++++

C:\Users\Moga\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

              precision    recall  f1-score   support

           0       0.73      0.96      0.83        73
           1       0.88      0.45      0.59        47

    accuracy                           0.76       120
   macro avg       0.80      0.70      0.71       120
weighted avg       0.79      0.76      0.74       120

[[70  3]
 [26 21]]
++++++++++++++++++++++++++++++++++++++
              precision    recall  f1-score   support

           0       0.97      0.92      0.94        73
           1       0.88      0.96      0.92        47

    accuracy                           0.93       120
   macro avg       0.93      0.94      0.93       120
weighted avg       0.94      0.93      0.93       120

[[67  6]
 [ 2 45]]
++++++++++++++++++++++++++++++++++++++
              precision    recall  f1-score   support

           0       0.82      0.95      0.88        73
           1       0.89      0.68      0.77        47

    accuracy                           0.84       120
   macro avg       0.86      0.81      0.83       120
weighted avg       0.85      0.84      0.84       120

[[69  4]
 [15 32]]
++++++++++++++++++++++++++++++++++++++

In [11]:
accuracy_df = pd.DataFrame()
accuracy_df['models'] =models_names
accuracy_df['Accuray'] =accuracy_models
accuracy_df = accuracy_df.set_index('models')
accuracy_df

                          Accuray
models
LogisticRegression       0.858333
RandomeForestClassifier  0.925000
KNeighborsClassifier     0.758333
DecisionTreeClassifier   0.933333
Support Vector Machine   0.841667